version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: cron
      cronjob: "0 9 * * 3,6"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      cronjob: "30 9 * * 3,6"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    groups:
      codeql-action:
        patterns:
          - github/codeql-action/*
